export const dossierTimeline = {
  entry: [0, 0.048],
  approach: [0.048, 0.096],
  open: [0.096, 0.163],
  chapters: [
    { story: [0.163, 0.259], hold: [0.259, 0.307], turn: [0.307, 0.369] },
    { story: [0.369, 0.465], hold: [0.465, 0.513], turn: [0.513, 0.575] },
    { story: [0.575, 0.671], hold: [0.671, 0.719], turn: [0.719, 0.781] },
    { story: [0.781, 0.877], hold: [0.877, 0.925], turn: null },
  ],
  close: [0.925, 1],
};

export const dossierMedia = {
  opportunitySite: {
    src: "/assets/dossier-v2/opportunity-site.webp",
    small: "/assets/dossier-v2/opportunity-site-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "50% 46%",
    alt: "Elevated view of the Devyog commercial footprint and landscaped podium at blue hour.",
  },
  opportunityActivity: {
    src: "/assets/dossier-v2/opportunity-activity.webp",
    small: "/assets/dossier-v2/opportunity-activity-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "52% 55%",
    alt: "Professionals meeting and working in a premium Devyog lobby and cafe environment.",
  },
  opportunityDestination: {
    src: "/assets/dossier-v2/opportunity-destination.webp",
    small: "/assets/dossier-v2/opportunity-destination-small.webp",
    width: 1200,
    height: 1600,
    aspect: "3 / 4",
    fit: "cover",
    position: "52% 58%",
    alt: "Completed Devyog mixed-use commercial destination with active offices and public realm at blue hour.",
  },
  locationIndia: {
    src: "/assets/dossier-v2/location-india-texture.webp",
    small: "/assets/dossier-v2/location-india-texture-small.webp",
    width: 1200,
    height: 1200,
    aspect: "1 / 1",
    fit: "cover",
    position: "center",
    alt: "Satellite-inspired terrain and city-light texture used inside the India map outline.",
  },
  locationMaharashtra: {
    src: "/assets/dossier-v2/location-maharashtra-texture.webp",
    small: "/assets/dossier-v2/location-maharashtra-texture-small.webp",
    width: 1200,
    height: 1200,
    aspect: "1 / 1",
    fit: "cover",
    position: "48% 50%",
    alt: "Regional terrain texture used inside the Maharashtra map outline.",
  },
  locationEastPune: {
    src: "/assets/dossier-v2/location-east-pune.webp",
    small: "/assets/dossier-v2/location-east-pune-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "54% 58%",
    alt: "Conceptual aerial view of an East Pune urban corridor with the Devyog destination highlighted in context.",
  },
  ecosystemWork: {
    src: "/assets/dossier-v2/ecosystem-work.webp",
    small: "/assets/dossier-v2/ecosystem-work-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "50% 48%",
    alt: "Premium collaborative office environment with focused work and glass meeting rooms.",
  },
  ecosystemArrival: {
    src: "/assets/dossier-v2/ecosystem-arrival.webp",
    small: "/assets/dossier-v2/ecosystem-arrival-small.webp",
    width: 1200,
    height: 1600,
    aspect: "3 / 4",
    fit: "cover",
    position: "50% 58%",
    alt: "Double-height Devyog lobby with reception, indoor planting and professionals arriving.",
  },
  ecosystemDining: {
    src: "/assets/dossier-v2/ecosystem-dining.webp",
    small: "/assets/dossier-v2/ecosystem-dining-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "52% 52%",
    alt: "Refined cafe and business-social environment opening to a landscaped terrace.",
  },
  ecosystemWellness: {
    src: "/assets/dossier-v2/ecosystem-wellness.webp",
    small: "/assets/dossier-v2/ecosystem-wellness-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "50% 52%",
    alt: "Landscaped workplace terrace with quiet wellness and social spaces at early evening.",
  },
  valuePlan: {
    src: "/assets/dossier-v2/value-flexible-plan.webp",
    small: "/assets/dossier-v2/value-flexible-plan-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "contain",
    position: "center",
    alt: "Contemporary flexible office floor plate with modular work and meeting configurations.",
  },
  valueInfrastructure: {
    src: "/assets/dossier-v2/value-infrastructure.webp",
    small: "/assets/dossier-v2/value-infrastructure-small.webp",
    width: 1600,
    height: 1200,
    aspect: "4 / 3",
    fit: "cover",
    position: "52% 50%",
    alt: "Organized smart-building infrastructure and commercial service core.",
  },
  valueExperience: {
    src: "/assets/dossier-v2/value-experience.webp",
    small: "/assets/dossier-v2/value-experience-small.webp",
    width: 1200,
    height: 1600,
    aspect: "3 / 4",
    fit: "cover",
    position: "50% 56%",
    alt: "Human-centred Devyog commercial public realm with active offices and evening landscape.",
  },
};

export const dossierChapters = [
  {
    id: "opportunity",
    number: "01",
    label: "Opportunity",
    marker: "Investment opportunity",
    title: ["Why this opportunity", "stands out"],
    copy: "More than square footage - a commercial destination shaped around demand, convenience and reasons to return.",
    pullQuote: ["Space is available.", "Relevance is designed."],
    statement: ["Not simply occupied.", "Actively chosen."],
    cta: "Explore the opportunity",
    route: "/investment-opportunity",
  },
  {
    id: "location",
    number: "02",
    label: "Location",
    marker: "Location & accessibility",
    title: ["Where growth", "converges"],
    copy: "A strategic East Pune address connected to expanding business, residential and urban movement.",
    pullQuote: ["From regional momentum", "to one connected address."],
    statement: ["From regional momentum", "to one connected address."],
    cta: "Explore location intelligence",
    route: "/location-accessibility",
  },
  {
    id: "ecosystem",
    number: "03",
    label: "Ecosystem",
    marker: "Demand ecosystem",
    title: ["Many uses.", "One active destination."],
    copy: "Work, meetings, dining, infrastructure and wellbeing create multiple reasons to arrive - and return.",
    pullQuote: ["Different reasons.", "Different moments."],
    statement: ["Different reasons. Different moments.", "One connected destination."],
    cta: "Explore the demand ecosystem",
    route: "/demand-ecosystem",
  },
  {
    id: "value",
    number: "04",
    label: "Long-term value",
    marker: "Long-term value",
    title: ["Built to adapt.", "Designed to remain relevant."],
    copy: "Flexible planning, integrated infrastructure and a complete commercial experience support changing business needs over time.",
    pullQuote: ["Built around change.", "Grounded in relevance."],
    statement: ["Designed to stay desired."],
    cta: "Explore long-term value",
    route: "/long-term-value",
  },
];

export const storyPages = {
  "/investment-opportunity": {
    number: "01",
    marker: "Investment opportunity",
    title: ["Why this opportunity", "stands out"],
    thesis: "A deeper look at how activity, experience and flexibility shape a modern commercial destination.",
    explore: ["Demand-led planning", "Everyday destination value", "Adaptable commercial space"],
    chapter: "opportunity",
  },
  "/location-accessibility": {
    number: "02",
    marker: "Location & accessibility",
    title: ["Where growth", "converges"],
    thesis: "A closer view of the project's relationship with business movement, residential growth and urban connectivity.",
    explore: ["East Pune context", "Movement and accessibility", "The project's connected setting"],
    chapter: "location",
  },
  "/demand-ecosystem": {
    number: "03",
    marker: "Demand ecosystem",
    title: ["Many uses.", "One active destination."],
    thesis: "Explore how workspaces, collaboration, convenience and lifestyle functions support different audiences throughout the day.",
    explore: ["Business audiences", "Connected amenities", "All-day activity"],
    chapter: "ecosystem",
  },
  "/long-term-value": {
    number: "04",
    marker: "Long-term value",
    title: ["Built to adapt.", "Designed to remain relevant."],
    thesis: "Explore how adaptable planning, integrated infrastructure and experience can support continued commercial desirability.",
    explore: ["Adaptable planning", "Integrated infrastructure", "Enduring experience"],
    chapter: "value",
  },
};
