export const dossierChapters = [
  {
    id: "opportunity",
    number: "01",
    label: "Opportunity",
    marker: "Investment opportunity",
    title: ["Why this opportunity", "stands out"],
    copy: "A commercial destination designed around business demand, everyday convenience and long-term relevance.",
    pullQuote: ["A building provides space.", "A destination creates reasons to return."],
    principle: "Space activates demand",
    statement: ["Not simply built to be occupied.", "Designed to stay desired."],
    cta: "Explore the opportunity",
    route: "/investment-opportunity",
    visual: "opportunity",
  },
  {
    id: "location",
    number: "02",
    label: "Location",
    marker: "Location & accessibility",
    title: ["Strategically positioned", "within East Pune’s evolving", "commercial corridor"],
    copy: "Connected to expanding business, residential and urban movement.",
    pullQuote: ["Movement creates access.", "Access concentrates opportunity."],
    principle: "From nation to address",
    statement: ["Movement converges", "around one connected address."],
    cta: "Explore location intelligence",
    route: "/location-accessibility",
    visual: "location",
  },
  {
    id: "ecosystem",
    number: "03",
    label: "Ecosystem",
    marker: "Demand ecosystem",
    title: ["Multiple uses.", "Multiple audiences.", "One connected destination."],
    copy: "A mixed-use environment designed to support business, collaboration, convenience and everyday activity.",
    pullQuote: ["Every use adds rhythm.", "Every audience strengthens the whole."],
    principle: "One integrated ecosystem",
    statement: ["Different users. Different times.", "One connected address."],
    cta: "Explore the demand ecosystem",
    route: "/demand-ecosystem",
    visual: "ecosystem",
  },
  {
    id: "value",
    number: "04",
    label: "Value",
    marker: "Long-term value",
    title: ["Designed for the present.", "Prepared for what comes next."],
    copy: "Flexible planning, integrated infrastructure and a complete commercial experience support long-term relevance.",
    pullQuote: ["Built around change.", "Grounded in enduring relevance."],
    principle: "Designed for adaptability",
    statement: ["Designed to stay desired."],
    cta: "Explore long-term value",
    route: "/long-term-value",
    visual: "value",
  },
];

export const storyPages = {
  "/investment-opportunity": {
    number: "01",
    marker: "Investment opportunity",
    title: ["Why this opportunity", "stands out"],
    thesis: "A deeper look at how demand, experience, flexibility and relevance shape a modern commercial destination.",
    explore: ["Demand-led planning", "Everyday destination value", "Adaptable commercial space"],
    chapter: "opportunity",
  },
  "/location-accessibility": {
    number: "02",
    marker: "Location & accessibility",
    title: ["Positioned within", "East Pune’s evolving", "commercial corridor"],
    thesis: "A closer view of the project’s relationship with business movement, residential growth and urban connectivity.",
    explore: ["East Pune context", "Movement and accessibility", "The project’s connected setting"],
    chapter: "location",
  },
  "/demand-ecosystem": {
    number: "03",
    marker: "Demand ecosystem",
    title: ["Multiple uses.", "One connected destination."],
    thesis: "Explore how workspaces, collaboration, convenience and lifestyle functions support different audiences throughout the day.",
    explore: ["Business audiences", "Connected amenities", "All-day activity"],
    chapter: "ecosystem",
  },
  "/long-term-value": {
    number: "04",
    marker: "Long-term value",
    title: ["Designed to remain relevant."],
    thesis: "Explore how adaptable planning, integrated infrastructure and experience can support continued commercial desirability.",
    explore: ["Adaptable planning", "Integrated infrastructure", "Enduring experience"],
    chapter: "value",
  },
};
