export const revenueModels = [
  {
    id: "lease",
    number: "01",
    selector: "Stability",
    label: "Long-term lease",
    title: ["Stability,", "structured over time."],
    description: "Long-duration occupancy designed around predictable use, professional management and consistent operation.",
    profile: [
      ["Income character", "Stable"],
      ["Investor involvement", "Lower"],
      ["Occupancy structure", "Long duration"],
    ],
    closing: "Built for investors who value consistency before complexity.",
    comparison: "Stable continuity",
    image: "/assets/revenue-architecture/stability.png",
    scores: { flexibility: 18, involvement: 18, horizon: 18 },
  },
  {
    id: "anchor",
    number: "02",
    selector: "Anchor",
    label: "Institutional anchor",
    title: ["Secure the base.", "Preserve the upside."],
    description: "A major occupier establishes the foundation while the remaining destination retains room for additional uses and income streams.",
    profile: [
      ["Base occupancy", "Established"],
      ["Ramp-up exposure", "Reduced"],
      ["Remaining potential", "Retained"],
    ],
    closing: "A stable foundation without surrendering the rest of the opportunity.",
    comparison: "Secure foundation",
    image: "/assets/revenue-architecture/anchor.png",
    scores: { flexibility: 44, involvement: 38, horizon: 34 },
  },
  {
    id: "blended",
    number: "03",
    selector: "Diversification",
    label: "Mixed-use blended",
    title: ["Many uses.", "One balanced income system."],
    description: "Offices, flexible work, dining and supporting facilities operate through different rhythms—within one connected destination.",
    profile: [
      ["Income character", "Diversified"],
      ["Activity window", "Extended"],
      ["Operational complexity", "Higher"],
    ],
    closing: "Different revenue rhythms supporting one connected asset.",
    comparison: "Diversified activity",
    image: "/assets/revenue-architecture/diversification.png",
    scores: { flexibility: 82, involvement: 82, horizon: 46 },
  },
  {
    id: "exit",
    number: "04",
    selector: "Exit",
    label: "Institutional exit",
    title: ["Build.", "Stabilise. Transfer."],
    description: "An institutional-grade asset prepared for long-hold capital, portfolio acquisition or a structured ownership transition.",
    profile: [
      ["Value event", "Transfer"],
      ["Asset condition", "Stabilised"],
      ["Buyer profile", "Institutional"],
    ],
    closing: "From development opportunity to investable institutional asset.",
    comparison: "Structured transfer",
    image: "/assets/revenue-architecture/exit.png",
    scores: { flexibility: 64, involvement: 28, horizon: 88 },
  },
];

export const revenueTimeline = {
  handoff: [0, 0.07],
  intro: [0.07, 0.14],
  models: [
    { story: [0.14, 0.20], hold: [0.20, 0.26], transition: [0.26, 0.30] },
    { story: [0.30, 0.36], hold: [0.36, 0.42], transition: [0.42, 0.46] },
    { story: [0.46, 0.52], hold: [0.52, 0.58], transition: [0.58, 0.62] },
    { story: [0.62, 0.68], hold: [0.68, 0.74], transition: [0.74, 0.78] },
  ],
  comparison: [0.78, 0.94],
  exit: [0.94, 1],
};
